### ISSUE TITLE
Analyze throws exceptions if no fonts, colors or font-sizes

### ISSUE THREAD

**Issue by mhemesath** [shiro16/ruby-stylestats#1]
If running style stats on a simple stylesheet with no fonts, colors or font-sizes, the analyzer throws an exception because those hashes don't exist. A nil check should be put in place to return 0, if those objects are nil

```sh
style_stats http://meyerweb.com/eric/tools/css/reset/reset.css
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/style_stats-0.3.0/lib/style_stats/configuration.rb:6: warning: duplicated key at line 8 ignored: :stylesheets
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/style_stats-0.3.0/lib/style_stats/css/analyze.rb:125:in `analyze_total_unique_font_families': undefined method `count' for nil:NilClass (NoMethodError)
	from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/style_stats-0.3.0/lib/style_stats/css/analyze.rb:27:in `analyze'
	from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/style_stats-0.3.0/lib/style_stats/template.rb:25:in `render'
	from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/style_stats-0.3.0/lib/style_stats.rb:33:in `render'
	from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/style_stats-0.3.0/lib/style_stats/cli.rb:12:in `run'
	from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/style_stats-0.3.0/exe/style_stats:32:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.1/bin/style_stats:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.1/bin/style_stats:23:in `<main>'
```

**Comment by shiro16** [comment]
https://github.com/shiro16/ruby-stylestats/pull/2
This pull request merged now.

Bug reports and fixes Thanks very much !

**Comment by mhemesath** [comment]
No problem, thanks for the tool!
